### ISSUE TITLE
Not sure what "provider" parameter is supposed to be. Getting error. 

### ISSUE THREAD

**Issue by alienfrenZyNo1** [TritonLabs/wonka#1]
I'm not quiet sure of what the provider parameter is expecting. Can someone please help? I've tried putting in devnet but getting below. 

`TypeError: Cannot read properties of undefined (reading '_buildArgs')
    at Function.<anonymous> (C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@metaplex-foundation\mpl-core\dist\src\Program.js:40:37)
    at Generator.next (<anonymous>)
    at C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@metaplex-foundation\mpl-core\dist\src\Program.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@metaplex-foundation\mpl-core\dist\src\Program.js:4:12)
    at Function.getProgramAccounts (C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@metaplex-foundation\mpl-core\dist\src\Program.js:23:16)
    at C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@triton-labs\wonka\lib\utils\metadata-utils.js:19:73
    at Generator.next (<anonymous>)
    at C:\Users\Marii\devprivate\solana\DiscordBotSimple\node_modules\@triton-labs\wonka\lib\utils\metadata-utils.js:8:71
    at new Promise (<anonymous>)`

**Comment by zkhalapyan** [comment]
Hey @alienfrenZyNo1, `[provider](https://project-serum.github.io/anchor/ts/classes/Provider.html)` is an object from project serum that allows easy ways to sign transactions, get access to the logged in wallet and access an ongoing connection. When you have Phantom installed, or one of the other Solana wallets, you should have access to `window.solana` which gives you access to what you need to create a Provider. If you go through our code below, you can find good examples of how get access to the provider. 

```JS
import { Connection, ConfirmOptions} from '@solana/web3.js';
import { Provider, Wallet } from '@project-serum/anchor';
import { Keypair } from '@solana/web3.js';

const providerOptions: ConfirmOptions = {
  // No idea what this does, someone look it up?
  preflightCommitment: 'processed',
};

/**
 * The provider is how web3 talks to the blockchain. Providers take JSON-RPC 
 * requests and return the response. This is normally done by submitting the 
 * request to an HTTP or IPC socket based server.
 * 
 * @returns Solana provider configured with the .env keys.
 */
const getProvider = (): Provider => {
  const solana = (window as any).solana
  return getProviderWithWallet(solana);
};

/**
 * Store the output of cat ~/.config/solana/id.json inside .env, and use the 
 * string to get a provider with this function. Useful for backend programs. 
 * 
 * @param secretKeyString Something like "[1, 2, 3, 4, 5...]"
 * @returns Solana provider configured with provided secret key.
 */
const getProviderWithSecretKeyString = (secretKeyString: string): Provider => {
  const secretKeyObject = JSON.parse(secretKeyString)
  const secretKey = new Uint8Array(secretKeyObject)
  const keypair = Keypair.fromSecretKey(secretKey)
  const payerWallet = new Wallet(keypair)
  const rpcHost = process.env.NEXT_PUBLIC_SOLANA_RPC_HOST;
  const connection = new Connection(rpcHost!);
  const provider = new Provider(
    connection,
    payerWallet,
    providerOptions
  );
  return provider;
};

const getProviderWithWallet = (wallet: Wallet): Provider => {
  const rpcHost = process.env.NEXT_PUBLIC_SOLANA_RPC_HOST;
  const connection = new Connection(rpcHost!);
  const provider = new Provider(
    connection,
    wallet,
    providerOptions
  );
  return provider;
};

export {
  getProvider,
  getProviderWithWallet,
  getProviderWithSecretKeyString
}
```

Let me know if this helps 🙂

**Comment by zkhalapyan** [comment]
Also, instructions if you're using wallet-adapter: [fetching anchor provider](https://github.com/solana-labs/wallet-adapter/issues/270#issuecomment-1017184894).
