### ISSUE TITLE
Expose price in `getCandyMachineState`?

### ISSUE THREAD

**Issue by edwardysun** [TritonLabs/wonka#2]
Would it be possible to also expose the price in the return result for `getCandyMachineState`? Thank you!

**Comment by edwardysun** [comment]
Perhaps this could be in a new method that just fetches some general config about the Candy Machine. I noticed in v1.0.7 of your library, there was a `candy-machine.js` that had a `getCandyMachineState` that exposed a bunch of stuff that was really useful for us, but it's since been removed in the latest version.

Thanks for creating this library. Super helpful overall

**Comment by zkhalapyan** [comment]
Just added 4e3fdcf1de46b5c8ebdb2d309ec695e679aadbed that exposes price and a handy function called `getMintPrice(..)` that helps with appropriate formatting. You can see an e2e example in the [next.js app](https://github.com/TritonLabs/wonka/blob/main/examples/next-js/pages/state.tsx#L29). 

The update also adds a lot more fields in the candy machine state, see the new interface: 

```JS
export interface CandyMachineState {
  itemsAvailable: number;
  itemsRedeemed: number;
  itemsRemaining: number;
  treasury: anchor.web3.PublicKey;
  tokenMint: anchor.web3.PublicKey;
  isSoldOut: boolean;
  isActive: boolean;
  isPresale: boolean;
  goLiveDate: Date;
  price: number;
  gatekeeper: null | {
    expireOnUse: boolean;
    gatekeeperNetwork: anchor.web3.PublicKey;
  };
  endSettings: null | {
    number: anchor.BN;
    endSettingType: any;
  };
  whitelistMintSettings: null | {
    mode: any;
    mint: anchor.web3.PublicKey;
    presale: boolean;
    discountPrice: null | number;
  };
  hiddenSettings: null | {
    name: string;
    uri: string;
    hash: Uint8Array;
  };
}
```

**Comment by zkhalapyan** [comment]
Also checkout f98fd22f8f30c2d7c66e9ff8004acaa20c920287, it's an _experimental_ tool we have been working on that fetches these things 10x faster; especially fetching NFTs for a particular collection has been super slow through metaplex/candy machine, so we have been internally using `Windex` i.e. Wonka Indexer.  See an example here [next.js](https://github.com/TritonLabs/wonka/blob/main/examples/next-js/pages/state.tsx#L46). 

You can also visually explore it with [GraphiQL](https://windex-api.onrender.com/api/v1/devnet/graphiql); just hit the play button. 

```
import { Windex } from '@triton-labs/wonka'
... 
// Sneak peak at Windex ;)
  useEffect(() => {
    async function fetch() {
      const windex = new Windex(process.env.NEXT_PUBLIC_CANDY_MACHINE_ID!)
      const collection = await windex.fetchCollection()
      console.log(collection)
    }
    fetch()
  }, [])
...

```

**Comment by edwardysun** [comment]
Awesome, looks great. Thank you!
